### ISSUE TITLE
Lexer does not ignore comments

### ISSUE THREAD

**Issue by pH34r-pH** [pH34r-pH/Classwork#6]
We need to add a case for the lexer so that when it encounters '#', it ignores the rest of the line

**Comment by nko12** [comment]
Does it [not already do that](https://github.com/pH34r-pH/Classwork/blob/cea3526d49280f749597b748dd03ec7bbfa82883/Scheduler/Lexer.c#L119)? If it didn't ignore the rest of the line, parsing would not occur properly.

**Comment by pH34r-pH** [comment]
Comments like #comment cause it to error out

**Comment by nko12** [comment]
You right, I'll get on it.

**Comment by nko12** [comment]
The reason this is a bug is because I wanted to protect against him naming a process with non alphanumeric characters, like "P1$5" or something like that. I guess we can assume he won't do something like that.
